IDEMPIERE-5567 Support of UUID as Key (FHCA-4195)
- Generate the int constructor even when the table doesn't have IDs, this is to avoid error on MappedModelFactory.scan, like
Sep 13, 2023 9:11:57 AM org.idempiere.model.MappedModelFactory scan
INFO: com.trekglobal.idempiere.rest.api.model.X_REST_RefreshToken.<init>(java.util.Properties,int,java.lang.String)
java.lang.NoSuchMethodException: com.trekglobal.idempiere.rest.api.model.X_REST_RefreshToken.<init>(java.util.Properties,int,java.lang.String)
        at java.base/java.lang.Class.getConstructor0(Class.java:3585)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
        at org.idempiere.model.MappedModelFactory.scan(MappedModelFactory.java:152)
        at com.trekglobal.idempiere.rest.api.Activator.start(Activator.java:41)