IDEMPIERE-5567 Support of UUID as Key (FHCA-4195)
- fix for import/export of TestUU_Trl
- fix for server stuck in loop when recent item doesn't have Record_UU
06:16:19.829===========> UiEngineImpl.handleError:  [131]
java.lang.IllegalArgumentException: Invalid null or blank UU - Must pass valid UU
        at org.compiere.model.PO.loadByUU(PO.java:1486)
        at org.compiere.model.MTable.getPOByUU(MTable.java:684)
        at org.compiere.model.MRecentItem.getLabel(MRecentItem.java:360)
        at org.adempiere.webui.dashboard.DPRecentItems.refresh(DPRecentItems.java:275)
        at org.adempiere.webui.dashboard.DPRecentItems.updateUI(DPRecentItems.java:333)